#!/usr/bin/env python3
"""Preview and select the deterministic harness-logo variants."""

from __future__ import annotations

import argparse
import os
from pathlib import Path

from agent_icons import PUA_LOGOS, TEXT_LOGOS, cell_width, font_available

AGENT_NAMES = {
    "claude": "Claude",
    "codex": "Codex",
    "opencode": "OpenCode",
    "omp": "OMP",
    "cline": "Cline",
    "mastracode": "MastraCode",
    "kimi": "Kimi",
    "kilo": "Kilo",
    "maki": "Maki",
}


def preview() -> str:
    lines = [
        "Herdr harness logo variants (plain terminal text; no ANSI)",
        f"Custom font detected: {'yes' if font_available() else 'no'}",
        "",
        "Harness     Font (PUA)       Text fallback",
        "----------  ---------------  -------------",
    ]
    for agent, name in AGENT_NAMES.items():
        glyph = PUA_LOGOS[agent]
        lines.append(
            f"{name:<10}  {glyph} U+{ord(glyph):04X} (w={cell_width(glyph)})  "
            f"{TEXT_LOGOS[agent]:<3} (w={cell_width(TEXT_LOGOS[agent])})"
        )
    lines.extend(
        (
            "",
            "auto: use the font only when Fontconfig finds it; otherwise text",
            "font: force exact PUA marks (tofu if the font is not configured)",
            "text: always use compact ASCII identifiers",
            "none: clear the logo token",
        )
    )
    return "\n".join(lines)


def write_selection(path: Path, variant: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        f'# Generated by the Herdr Agent Icons preview picker.\nvariant = "{variant}"\n',
        encoding="ascii",
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--pick", action="store_true")
    parser.add_argument("--select", choices=("auto", "font", "text", "none"))
    parser.add_argument("--config", type=Path)
    args = parser.parse_args()
    print(preview())

    selection = args.select
    if args.pick:
        selection = input("\nSelect auto/font/text/none (Enter keeps current): ").strip() or None
        if selection is not None and selection not in {"auto", "font", "text", "none"}:
            raise SystemExit(f"invalid selection: {selection}")
    if selection is None:
        return 0

    config_path = args.config
    if config_path is None:
        config_dir = os.environ.get("HERDR_PLUGIN_CONFIG_DIR")
        if not config_dir:
            raise SystemExit("--config is required outside a Herdr plugin invocation")
        config_path = Path(config_dir) / "config.toml"
    write_selection(config_path, selection)
    print(f"Selected {selection}; wrote {config_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
